//
// Purpur Tentakel
// 08.06.2023
//

#pragma once
#include <string>

enum class ConfigTypes {
	CONFIFG,

	FIGHT,
	HIT_CHANCE,
	FLEET_FIGHT_RANGE,

	FLEET,
	FLEET_SPEED_CURRENT,
	FLEET_SPEED_MAX,
	FLEET_SPEED_MIN,

	GLOBAL,
	GAME_ROUNDS_CURRENT,
	GAME_ROUNDS_MAX,
	GAME_ROUNDS_MIN,

	PLANET,
	PRODUCTION_HOMEWORLD,
	PRODUCTION_MAX,
	PRODUCTION_MIN,
	SHIPS_MAX_FACTOR,
	SPACEING_GLOBAL,
	SPACEING_HOMEWORLD,
	STARTING_SHIPS_MULTIPLICATOR_GLOBAL,
	STARTING_SHIPS_MULTIPLICATOR_HUMAN,

	PLAYER,
	PLAYER_COUNT_MAX,
	PLAYER_COUNT_MIN,

	SOUND,
	VOLUME_MASTER,
	VOLUME_MUTE_BOOL,

	VERSION,
	VERSION_CONFIG,
	VERSION_GAME,

	WINDOW,
	RESOLUTION_AS_ENUM,
	FULL_SCREEN_START_BOOL,
	TARGET_FPS,

	WORLD,
	DIMENSION_X_CURRENT,
	DIMENSION_X_MAX,
	DIMENSION_X_MIN,
	DIMENSION_X_SHOW_GALAXY,
	DIMENSION_Y_CURRENT,
	DIMENSION_Y_MAX,
	DIMENSION_Y_MIN,
	DIMENSION_Y_SHOW_GALAXY,
	DISCOVER_RANGE,
	PLANET_COUNT_CURRENT,
	PLANET_COUNT_MAX,
	PLANET_COUNT_MIN,
	PLANET_COUNT_SHOW_GALAXY,
};

[[nodiscard]] std::string CToS(ConfigTypes type);
